IF EXISTS(SELECT 1 FROM dbo.Auctus_Holidays WHERE DATEPART(YEAR,Date)=DATEPART(YEAR,GETDATE()))
PRINT 1
ELSE
BEGIN
	DECLARE @Date DATE=CONVERT(DATE,CONVERT(VARCHAR(10),DATEPART(YEAR,GETDATE()))+'-01-01')
	DECLARE @nextYear DATE=CONVERT(DATE,CONVERT(VARCHAR(10),DATEPART(YEAR,GETDATE())+1)+'-01-01')
	WHILE @Date<@nextYear
	BEGIN
		IF DATEPART(WEEKDAY,@Date)=1 OR DATEPART(WEEKDAY,@Date)=7
		BEGIN
			INSERT INTO dbo.Auctus_Holidays
			        ( Date )
			VALUES  ( @Date  -- Date - date
			          )
		END		
		SET @Date=DATEADD(DAY,1,@Date)
	END 
	SELECT @Date
END
