
/****** Object:  Table [dbo].[Auctus_Bom]    Script Date: 2018/8/24 9:32:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Auctus_Bom](
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[Code] [VARCHAR](50) NULL,
	[Name] [NVARCHAR](255) NULL,
	[SPEC] [NVARCHAR](MAX) NULL,
	[Line] [VARCHAR](10) NULL,
	Num VARCHAR(10) NULL,
	Version VARCHAR(20),
	Cost VARCHAR(20),
	Weight VARCHAR(20),
	BOMUom VARCHAR(20),
	BaseNum VARCHAR(20),
	Waste VARCHAR(20),
	Position nVARCHAR(1000),
	Remark NVARCHAR(MAX),
	[CreateDate] [DATETIME] NULL,
	[No] [INT] NOT NULL,
 CONSTRAINT [PK__Auctus_B__3214EC274288ED91] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[Auctus_Bom] ADD  CONSTRAINT [DF_Auctus_Bom_No]  DEFAULT ((1)) FOR [No]
GO




